#!/usr/bin/env bash
ARCHIVE="https://odooku.s3.amazonaws.com/heroku-16/libraries/vendor/openldap.tar.gz"

if [ ! -f ".heroku/vendor/lib/libldap.so" ]; then
  puts-step "Bootstrapping openLDAP"
  mkdir -p .heroku/vendor
  curl -s $ARCHIVE 2> /dev/null | tar zxv -C .heroku/vendor &> /dev/null
fi
